### ISSUE TITLE
Can you provide detailed training and validation code and related library dependencies?

### ISSUE THREAD

**Issue by qczggaoqiang** [CXH-Research/SMAFormer#1]
Hi! Can you provide detailed training and validation code and related library dependencies?  I'd appreciate it if you could.

**Comment by xuhangc** [comment]
> Hi! Can you provide detailed training and validation code and related library dependencies? I'd appreciate it if you could.

You may refer to the details [here](https://github.com/lzeeorno/SMAFormer). This repo only contains the backbone model.
